CREATE TABLE IF NOT EXISTS post_admission_team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(500) NOT NULL,
  experience INT NOT NULL DEFAULT 0,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  assist_student INT NOT NULL DEFAULT 0,
  connection_link VARCHAR(500) DEFAULT NULL,
  label VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
