-- Migration: KYC form submissions

CREATE TABLE IF NOT EXISTS `kyc_forms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL,
  `dob` VARCHAR(32) DEFAULT NULL,
  `mobile` VARCHAR(20) NOT NULL,
  `alt_mobile` VARCHAR(20) DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `pan` VARCHAR(20) DEFAULT NULL,
  `aadhaar` VARCHAR(20) DEFAULT NULL,
  `gender` VARCHAR(20) DEFAULT NULL,
  `shop_name` VARCHAR(255) DEFAULT NULL,
  `biz_type` VARCHAR(150) DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `locality` VARCHAR(255) DEFAULT NULL,
  `city` VARCHAR(150) DEFAULT NULL,
  `pincode` VARCHAR(20) DEFAULT NULL,
  `google_loc` VARCHAR(512) DEFAULT NULL,
  `footfall` VARCHAR(50) DEFAULT NULL,
  `acc_holder` VARCHAR(150) DEFAULT NULL,
  `bank_name` VARCHAR(150) DEFAULT NULL,
  `acc_number` VARCHAR(50) DEFAULT NULL,
  `ifsc` VARCHAR(20) DEFAULT NULL,
  `upi` VARCHAR(100) DEFAULT NULL,
  `doc_id` VARCHAR(512) DEFAULT NULL,
  `doc_pan` VARCHAR(512) DEFAULT NULL,
  `doc_shop_addr` VARCHAR(512) DEFAULT NULL,
  `doc_cheque` VARCHAR(512) DEFAULT NULL,
  `doc_photo_out` VARCHAR(512) DEFAULT NULL,
  `doc_photo_in` VARCHAR(512) DEFAULT NULL,
  `coi` VARCHAR(20) DEFAULT NULL,
  `coi_specify` VARCHAR(255) DEFAULT NULL,
  `declaration_agree` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_kyc_forms_email` (`email`),
  KEY `idx_kyc_forms_mobile` (`mobile`),
  KEY `idx_kyc_forms_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
